name:                thock
version:             0.3.0.0
github:              "rmehri01/thock"
license:             MIT
author:              "Ryan Mehri"
maintainer:          "ryan.mehri1@gmail.com"
copyright:           "Copyright (c) 2020 Ryan Mehri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A modern TUI typing game featuring online racing against friends.
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rmehri01/thock#readme>

dependencies:
- aeson       >= 1.5.5.1 && < 1.6
- base        >= 4.7 && < 5
- brick       >= 0.58.1 && < 0.59
- containers  >= 0.6.2.1 && < 0.7
- file-embed  >= 0.0.11.2 && < 0.1
- lens        >= 4.19.2 && < 4.20
- mtl         >= 2.2.2 && < 2.3
- network     >= 3.1.1.1 && < 3.2
- random      == 1.1.*
- text        >= 1.2.3.0 && < 1.3
- text-zipper >= 0.11 && < 0.12
- time        >= 1.9.3 && < 1.10
- vector      >= 0.12.1.2 && < 0.13
- vty         >= 5.32 && < 5.33
- websockets  >= 0.12.7.1 && < 0.13

default-extensions:
  FlexibleContexts
  OverloadedStrings
  TypeApplications

library:
  source-dirs: src

executables:
  thock:
    main:                thock/Main.hs
    source-dirs:         app
    ghc-options:
    - -O3
    #- -optl-static
    - -rtsopts
    - -static
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    cc-options:
      - -static
    ld-options:
      - -static
      - -pthread
    dependencies:
    - thock
  server:
    main:                server/Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - thock

tests:
  thock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - thock
